# Generated by Django 4.1.1 on 2023-02-06 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='body',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
