# Generated by Django 4.1.1 on 2023-02-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
