# Generated by Django 4.1.1 on 2023-02-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_coordinator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
