# Generated by Django 4.1.1 on 2023-01-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_updates',
            name='Final_Score',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_updates',
            name='Goal_Scorers_TEAM_1',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_updates',
            name='Goal_Scorers_TEAM_2',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_updates',
            name='Team_1',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_updates',
            name='Team_2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_updates',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
