# Generated by Django 4.1.1 on 2023-01-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Batch',
            field=models.BigIntegerField(default=2075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
