# Generated by Django 4.1.1 on 2023-01-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_batch_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Email',
        ),
    ]
