# Generated by Django 4.1.1 on 2023-02-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
