# Generated by Django 4.1.1 on 2023-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_customuser_delete_user_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='batch',
        ),
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
