# Generated by Django 4.1.1 on 2023-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCoordinator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_registration',
            old_name='title',
            new_name='Team_Name',
        ),
        migrations.AddField(
            model_name='team_registration',
            name='Goal_Keeper',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
