# Generated by Django 4.1.1 on 2023-01-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCoordinator', '0003_team_registration_captain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_Registration',
        ),
    ]
